language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: DucklingHTTPExtractor
    url: http://localhost:8000
    dimensions:
    - amount-of-money
    - time
    - number
  - name: "SpacyNLP"
    model: "en_core_web_md"
  - name: "SpacyEntityExtractor"
    dimensions: ["PERSON"]

policies:
- name: TEDPolicy
  max_history: 10
  epochs: 20
  batch_size:
  - 32
  - 64
- max_history: 6
  name: AugmentedMemoizationPolicy
- core_threshold: 0.3
  name: TwoStageFallbackPolicy
  nlu_threshold: 0.8
  deny_suggestion_intent_name: "trigger_rephrase"
- name: FormPolicy
- name: MappingPolicy
